trigger:
  - main  # Trigger pipeline on pushes to the main branch (or any branch you prefer)

pool:
  vmImage: 'ubuntu-latest'  # Use a hosted Ubuntu agent for the build

steps:
  # Step 1: Checkout the code
  - checkout: self

  # Step 2: Build the WAR file using Maven
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'  # Path to your Maven pom.xml file
      goals: 'clean package'  # Use Maven clean and package to build the WAR file
      options: '-DskipTests'  # Skip tests if needed
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'  # Specify the JDK version to use
      jdkArchitecture: 'x64'

  # Step 3: Deploy the WAR file to Azure Artifacts (Maven feed)
  - task: Maven@3
    displayName: 'Deploy WAR to Azure Artifacts'
    inputs:
      mavenPomFile: 'pom.xml'  # Path to your Maven pom.xml file
      goals: 'deploy'  # Maven deploy goal to push the WAR file to the repository
      mavenOptions: '-Xmx3072m'  # Optional: Adjust memory if needed
	  options: |
        -DskipTests
        -DaltDeploymentRepository=azure-artifacts::default::https://pkgs.dev.azure.com/meenar34/Demo/_artifacts/feed/my-artifacts-feed/maven/v1
        -Dusername=meena
        -Dpassword=$(System.AccessToken)  # System.AccessToken is used for authentication in Azure Pipelines
